[package]
name = "sqlp"
version = "1.0.0"
description = "sqlp"
authors = ["tansen"]
license = "MIT"
repository = ""
default-run = "sqlp"
edition = "2021"
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib/mod.rs"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
csv = "1.3.0"
chrono = "0.4.34"
serde = { version = "1.0.196", features = ["derive"] }
tauri = { version = "1.5.4", features = [ "api-all"] }
polars = { version = "0.38.3", features = [
    "lazy",
    "diagonal_concat",
    "streaming",
    "asof_join",
    "cross_join",
    "semi_anti_join",
    "sql",
    "cse",
    "csv",
    ] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
