[package]
name = "InsightSQL"
version = "1.0.4"
description = "InsightSQL"
authors = ["tansen"]
license = "MIT"
repository = ""
default-run = "InsightSQL"
edition = "2021"
rust-version = "1.81.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib/mod.rs"

[build-dependencies]
tauri-build = { version = "1.5.5", features = [] }

[dependencies]
calamine = { version = "0.25", features = ["dates"] }
chrono = "0.4.38"
csv = "1.3.0"
serde = { version = "1", features = ["derive"] }
tauri = { version = "1.8.0", features = [ "api-all"] }
itoa = "1"
polars = { version = "0.43.1", features = [
    "lazy",
    "diagonal_concat",
    # "streaming",
    "asof_join",
    "cross_join",
    "semi_anti_join",
    "sql",
    # "cse",
    "csv",
    "parquet",
    ] }
rayon = "1.10.0"
rust_xlsxwriter = "0.76.0"
ryu = "1"
serde_json = "1"
indexmap = {version = "2.5.0", features = ["serde"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
